name: Update gist with WakaTime stats
on:
  workflow_dispatch:
  push:
    branches: master
  schedule:
    # - cron: "0 */3 * * *"
    - cron: "*/30 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@v4.0.5
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 9893641e97e0bdd35549960db98a9c1f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
